version: "2"
services:
  web:
      build: .
      ports:
          - '8089:4200'
      volumes:
          - .:/usr/src/app/
      environment:
          - NODE_ENV=dev
      command: bash -c "npm start"